module RTI {

module RecordingService {

const int32 DATA_TAG_MAX_STRING_SIZE = 256;

struct DataTagParams {
    float timestamp_offset;
    string<DATA_TAG_MAX_STRING_SIZE> tag_name;
    string tag_description;
};

// Breakpoint
enum BreakpointFormat {
    TIMESTAMP = 0,
    TAG_NAME
};

/*
 * Breakpoint union to allow the user to choose
 * the breakpoint representation.
 *
 * - timestamp_nanos: Timestamp of the breakpoint
 *
 * - tag_name: it refers to one of the tags stored in the tags table inside
 *   the SQlite metadata file
 */
@nested
union BreakpointUnion switch (BreakpointFormat) {
case TIMESTAMP:
    int64 timestamp_nanos;
case TAG_NAME:
    string<DATA_TAG_MAX_STRING_SIZE> tag_name;
};

struct BreakpointParams {
    @optional string<DATA_TAG_MAX_STRING_SIZE> label;

    BreakpointUnion value;
};

// Continue
enum ContinueFormat {
    OFFSET = 0,
    SLICE
};

@nested
union ContinueUnion switch (ContinueFormat) {
case OFFSET:
    int64 offset;
case SLICE:
    int64 slices;
};

struct ContinueParams {
    ContinueUnion value;
};

// DebugStatus
enum TimerState {
    WORKING = 0,
    PAUSED,
    BREAKPOINT
};

struct DebugStatus {
    TimerState status;
};

// TimestampHolder
struct TimestampHolder {
    // timestamp in nanoseconds
    int64 timestamp_nanos;
};

}; // module RecordingService
}; // module RTI
