"""Headless application core for rs_gui_v2."""

from .events import AppCommand, AppEvent, CommandResult, CommandStatus, LifecyclePhase
from .discovery import (
    DiscoveredEndpoint,
    DiscoveredTopic,
    EndpointDirection,
    FakeTopicDiscoveryClient,
    TopicDiscoveryFacade,
    TopicDiscoveryState,
    TopicInventory,
    TopicSelection,
    TopicSelectionState,
)
from .runtime import AppRuntime, RuntimeConfig
from .services import (
    AdminReadiness,
    AdminReadinessStatus,
    FakeServiceAdminClient,
    FakeServiceMonitoringClient,
    MonitoringSnapshot,
    MonitoringSnapshotKind,
    ServiceAdminClient,
    ServiceAdminFacade,
    ServiceCommand,
    ServiceCommandOutcome,
    ServiceCommandRequest,
    ServiceInstanceRef,
    ServiceKind,
    ServiceMonitoringClient,
    ServiceMonitoringFacade,
    ServiceStateSnapshot,
)
from .state import AppState
from .types import TypeAvailabilityStatus, TypeCatalog, TypeResolution

__all__ = [
    "AdminReadiness",
    "AdminReadinessStatus",
    "AppCommand",
    "AppEvent",
    "AppRuntime",
    "AppState",
    "CommandResult",
    "CommandStatus",
    "DiscoveredEndpoint",
    "DiscoveredTopic",
    "EndpointDirection",
    "FakeTopicDiscoveryClient",
    "FakeServiceAdminClient",
    "FakeServiceMonitoringClient",
    "LifecyclePhase",
    "MonitoringSnapshot",
    "MonitoringSnapshotKind",
    "RuntimeConfig",
    "ServiceAdminClient",
    "ServiceAdminFacade",
    "ServiceCommand",
    "ServiceCommandOutcome",
    "ServiceCommandRequest",
    "ServiceInstanceRef",
    "ServiceKind",
    "ServiceMonitoringClient",
    "ServiceMonitoringFacade",
    "ServiceStateSnapshot",
    "TopicDiscoveryFacade",
    "TopicDiscoveryState",
    "TopicInventory",
    "TopicSelection",
    "TopicSelectionState",
    "TypeAvailabilityStatus",
    "TypeCatalog",
    "TypeResolution",
]