# (c) Copyright, Real-Time Innovations, 2026.  All rights reserved.
# RTI grants Licensee a license to use, modify, compile, and create derivative
# works of the software solely for use with RTI Connext DDS. Licensee may
# redistribute copies of the software provided that all such copies are subject
# to this license. The software is provided "as is", with no warranty of any
# type, including any warranty for fitness for any purpose. RTI is under no
# obligation to maintain or support the software. RTI shall not be liable for
# any incidental or consequential damages arising out of the use or inability
# to use the software.
"""Session and view-model helpers for rs_gui."""

from .factory import (
    GuiShellAssembly,
    GuiShellSessionFactoryConfig,
    GuiShellSessionMode,
    build_default_gui_shell_session,
    build_gui_shell_assembly,
)
from .scheduler import UiFrameScheduler
from .session import GuiShellSession, GuiShellSessionConfig
from .workspace import GuiWorkspaceController, GuiWorkspaceControllerConfig
from .tabs import (
    ConvertActionView,
    ConvertJobRow,
    ConvertLogRow,
    ConvertPresetView,
    ConvertStorageView,
    ConvertTabViewModel,
    ConvertTabController,
    ConvertTabControllerConfig,
    ConverterServiceFacade,
    ConverterServiceConfig,
    PlotsTabController,
    PlotsTabControllerConfig,
    RecordTabController,
    RecordTabControllerConfig,
    ReplayActionView,
    ReplayTargetRow,
    ReplayTabController,
    ReplayTabControllerConfig,
    ReplayTabViewModel,
    ReplayTimelineRow,
    TopicsTabController,
    TopicsTabControllerConfig,
    build_convert_action_command,
    build_convert_tab_view_model,
    build_mock_convert_tab_view_model,
    build_mock_replay_tab_view_model,
    build_replay_action_command,
    build_replay_tab_view_model,
    plots_inputs_from_data_session_snapshot,
    topics_inputs_from_data_session_snapshot,
)
from .tabs.plots_tab import (
    PlotActionView,
    PlotPointRow,
    PlotRow,
    PlotSeriesRow,
    PlotsTabViewModel,
    build_mock_plots_tab_view_model,
    build_plots_tab_view_model,
)
from .tabs.topics_tab import (
    SampleInspectorRow,
    TopicActionView,
    TopicFieldRow,
    TopicRow,
    TopicsTabViewModel,
    build_topic_action_command,
    build_topic_field_command,
    build_topic_select_command,
    build_mock_topics_tab_view_model,
    build_topics_tab_view_model,
)
from .view_models import (
    EventLogEntry,
    ShellStatusItem,
    ShellViewModel,
    build_mock_shell_view_model,
    build_shell_view_model,
)

__all__ = [
    "EventLogEntry",
    "GuiShellAssembly",
    "GuiShellSession",
    "GuiShellSessionConfig",
    "GuiShellSessionFactoryConfig",
    "GuiShellSessionMode",
    "GuiWorkspaceController",
    "GuiWorkspaceControllerConfig",
    "ConvertActionView",
    "ConvertJobRow",
    "ConvertLogRow",
    "ConvertPresetView",
    "ConvertStorageView",
    "ConvertTabViewModel",
    "ConvertTabController",
    "ConvertTabControllerConfig",
    "ConverterServiceFacade",
    "ConverterServiceConfig",
    "PlotActionView",
    "PlotPointRow",
    "PlotRow",
    "PlotSeriesRow",
    "PlotsTabController",
    "PlotsTabControllerConfig",
    "PlotsTabViewModel",
    "RecordTabController",
    "RecordTabControllerConfig",
    "ReplayActionView",
    "ReplayTargetRow",
    "ReplayTabController",
    "ReplayTabControllerConfig",
    "ReplayTabViewModel",
    "ReplayTimelineRow",
    "SampleInspectorRow",
    "ShellStatusItem",
    "ShellViewModel",
    "TopicActionView",
    "TopicFieldRow",
    "TopicRow",
    "TopicsTabController",
    "TopicsTabControllerConfig",
    "TopicsTabViewModel",
    "UiFrameScheduler",
    "build_default_gui_shell_session",
    "build_convert_action_command",
    "build_convert_tab_view_model",
    "build_gui_shell_assembly",
    "build_mock_convert_tab_view_model",
    "build_mock_plots_tab_view_model",
    "build_mock_replay_tab_view_model",
    "build_mock_shell_view_model",
    "build_mock_topics_tab_view_model",
    "build_plots_tab_view_model",
    "build_replay_action_command",
    "build_replay_tab_view_model",
    "build_shell_view_model",
    "build_topic_action_command",
    "build_topic_field_command",
    "build_topic_select_command",
    "build_topics_tab_view_model",
    "plots_inputs_from_data_session_snapshot",
    "topics_inputs_from_data_session_snapshot",
]
