#!/bin/bash
# Run script for Example I/O Application (Python).

set -euo pipefail

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
source "$REPO_ROOT/scripts/python_env.sh"

echo "=== Example I/O Application (Python) ==="
echo
python_env_init "example_io_app" "$REPO_ROOT"
python_env_resolve_nddshome
python_env_ensure_venv
python_env_activate_venv
python_env_sync_requirements "$REPO_ROOT/apps/python/requirements.txt" "rti.connextdds:RTI Connext DDS Python API"
python_env_resolve_license_file

# --- Versioned Python Type Support ---
echo
# Detect installed rti.connext version
RTI_PYTHON_VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('rti-connext'))" 2>/dev/null || \
    python -c "import pkg_resources; print(pkg_resources.get_distribution('rti-connext').version)" 2>/dev/null || \
    echo "")

if [ -z "$RTI_PYTHON_VERSION" ]; then
    echo "ERROR: Cannot detect rti.connext version. Is the package installed?"
    echo "  pip install rti.connext"
    exit 1
fi
echo "✓ Detected rti.connext version: $RTI_PYTHON_VERSION"

# Versioned types cache directory
TYPES_CACHE_DIR="$REPO_ROOT/build/dds/python_types"
VERSIONED_DIR="$TYPES_CACHE_DIR/$RTI_PYTHON_VERSION/python_gen"
IDL_DIR="$REPO_ROOT/dds/datamodel/idl"

# Check if we can verify version from existing generated types
check_generated_version() {
    local gen_file="$1"
    if [ -f "$gen_file" ]; then
        # Generated files contain: "# using RTI Code Generator (rtiddsgen) version X.Y.Z."
        grep -oP 'rtiddsgen\) version \K[0-9]+\.[0-9]+\.[0-9]+' "$gen_file" 2>/dev/null || echo ""
    fi
}

if [ -f "$VERSIONED_DIR/ExampleTypes.py" ]; then
    GENERATED_VERSION=$(check_generated_version "$VERSIONED_DIR/ExampleTypes.py")
    echo "✓ Found cached types (generated by rtiddsgen $GENERATED_VERSION)"
else
    echo "Generating Python type support for rti.connext $RTI_PYTHON_VERSION..."

    # Ensure rtiddsgen is available from NDDSHOME
    RTIDDSGEN="$NDDSHOME/bin/rtiddsgen"
    if [ ! -x "$RTIDDSGEN" ]; then
        echo "ERROR: rtiddsgen not found at $RTIDDSGEN"
        echo "  Ensure NDDSHOME points to a valid Connext installation."
        exit 1
    fi

    mkdir -p "$VERSIONED_DIR"

    # Query the runtime XTypes compliance mask so generated code matches
    XTYPES_MASK=$(python -c "import rti.connextdds as dds; print(hex(int(dds.compliance.get_xtypes_mask())))" 2>/dev/null || echo "")

    # Generate Python types for each IDL file
    for IDL_FILE in "$IDL_DIR"/*.idl; do
        IDL_BASENAME=$(basename "$IDL_FILE" .idl)
        echo "  Generating: $IDL_BASENAME..."
        if [ -n "$XTYPES_MASK" ]; then
            "$RTIDDSGEN" -language Python -d "$VERSIONED_DIR" \
                -I "$IDL_DIR" -xTypesComplianceMask "$XTYPES_MASK" \
                "$IDL_FILE" -replace 2>&1 | grep -v "^$" || true
        else
            "$RTIDDSGEN" -language Python -d "$VERSIONED_DIR" \
                -I "$IDL_DIR" "$IDL_FILE" -replace 2>&1 | grep -v "^$" || true
        fi
    done

    # Create __init__.py if not generated
    if [ ! -f "$VERSIONED_DIR/__init__.py" ]; then
        touch "$VERSIONED_DIR/__init__.py"
    fi

    if [ ! -f "$VERSIONED_DIR/ExampleTypes.py" ]; then
        echo "ERROR: Type generation failed. ExampleTypes.py not created."
        exit 1
    fi

    GENERATED_VERSION=$(check_generated_version "$VERSIONED_DIR/ExampleTypes.py")
    echo "✓ Generated types using rtiddsgen $GENERATED_VERSION"
fi

# --- Run Application ---
echo
echo "Starting Example I/O Application..."
echo "-----------------------------------"
# Set the versioned types path so the app can find python_gen package
export DDS_PYTHON_GEN_DIR="$TYPES_CACHE_DIR/$RTI_PYTHON_VERSION"
export PYTHONPATH="$TYPES_CACHE_DIR/$RTI_PYTHON_VERSION${PYTHONPATH:+:$PYTHONPATH}"
cd "$SCRIPT_DIR"
python example_io_app.py "$@"
