#!/bin/bash
# Run script for Example I/O Application (Python)
# Handles environment setup and executes the application

set -e  # Exit on any error

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "=== Example I/O Application (Python) ==="
echo

# --- NDDSHOME Auto-Detection ---
if [ -z "$NDDSHOME" ]; then
    echo "NDDSHOME not set. Searching for RTI Connext installation..."
    
    # Find latest version in ~/rti_connext_dds-*
    LATEST_RTI=$(ls -d ~/rti_connext_dds-* 2>/dev/null | sort -V | tail -n 1)
    
    if [ -n "$LATEST_RTI" ] && [ -d "$LATEST_RTI" ]; then
        export NDDSHOME="$LATEST_RTI"
        echo "✓ Found RTI installation: $NDDSHOME"
    else
        echo "ERROR: NDDSHOME not set and no RTI installation found in ~/rti_connext_dds-*"
        echo ""
        echo "Please either:"
        echo "  1. Set NDDSHOME environment variable:"
        echo "     export NDDSHOME=/path/to/rti_connext_dds-x.x.x"
        echo ""
        echo "  2. Install RTI Connext DDS in your home directory"
        echo ""
        exit 1
    fi
else
    echo "✓ NDDSHOME: $NDDSHOME"
fi

# --- License File Validation (Required for Python) ---
echo
echo "Checking for RTI license file..."
LICENSE_FOUND=false

if [ -n "$RTI_LICENSE_FILE" ] && [ -f "$RTI_LICENSE_FILE" ]; then
    echo "✓ Using license from RTI_LICENSE_FILE: $RTI_LICENSE_FILE"
    LICENSE_FOUND=true
elif [ -f "$NDDSHOME/rti_license.dat" ]; then
    export RTI_LICENSE_FILE="$NDDSHOME/rti_license.dat"
    echo "✓ Using license from NDDSHOME: $RTI_LICENSE_FILE"
    LICENSE_FOUND=true
elif [ -f "$SCRIPT_DIR/rti_license.dat" ]; then
    export RTI_LICENSE_FILE="$SCRIPT_DIR/rti_license.dat"
    echo "✓ Using license from app directory: $RTI_LICENSE_FILE"
    LICENSE_FOUND=true
fi

if [ "$LICENSE_FOUND" = false ]; then
    echo "ERROR: RTI license file not found."
    echo ""
    echo "Please either:"
    echo "  1. Set RTI_LICENSE_FILE environment variable:"
    echo "     export RTI_LICENSE_FILE=/path/to/rti_license.dat"
    echo ""
    echo "  2. Place rti_license.dat in \$NDDSHOME:"
    echo "     cp /path/to/rti_license.dat $NDDSHOME/"
    echo ""
    exit 1
fi

# --- Virtual Environment Activation ---
echo
VENV_DIR="$REPO_ROOT/connext_dds_env"
if [ ! -d "$VENV_DIR" ]; then
    echo "Virtual environment not found. Running install script..."
    echo ""
    
    "$REPO_ROOT/apps/python/install.sh"
    
    if [ ! -d "$VENV_DIR" ]; then
        echo "ERROR: Failed to create virtual environment."
        echo "Please check install script output for errors."
        exit 1
    fi
fi

echo "Activating virtual environment..."
source "$VENV_DIR/bin/activate" 2>/dev/null || true
export PATH="$VENV_DIR/bin:$PATH"
echo "✓ Virtual environment activated"

# --- Versioned Python Type Support ---
echo
# Detect installed rti.connext version
RTI_PYTHON_VERSION=$(python3 -c "import importlib.metadata; print(importlib.metadata.version('rti-connext'))" 2>/dev/null || \
    python3 -c "import pkg_resources; print(pkg_resources.get_distribution('rti-connext').version)" 2>/dev/null || \
    echo "")

if [ -z "$RTI_PYTHON_VERSION" ]; then
    echo "ERROR: Cannot detect rti.connext version. Is the package installed?"
    echo "  pip install rti.connext"
    exit 1
fi
echo "✓ Detected rti.connext version: $RTI_PYTHON_VERSION"

# Versioned types cache directory
TYPES_CACHE_DIR="$REPO_ROOT/build/dds/python_types"
VERSIONED_DIR="$TYPES_CACHE_DIR/$RTI_PYTHON_VERSION/python_gen"
IDL_DIR="$REPO_ROOT/dds/datamodel/idl"

# Check if we can verify version from existing generated types
check_generated_version() {
    local gen_file="$1"
    if [ -f "$gen_file" ]; then
        # Generated files contain: "# using RTI Code Generator (rtiddsgen) version X.Y.Z."
        grep -oP 'rtiddsgen\) version \K[0-9]+\.[0-9]+\.[0-9]+' "$gen_file" 2>/dev/null || echo ""
    fi
}

if [ -f "$VERSIONED_DIR/ExampleTypes.py" ]; then
    GENERATED_VERSION=$(check_generated_version "$VERSIONED_DIR/ExampleTypes.py")
    echo "✓ Found cached types (generated by rtiddsgen $GENERATED_VERSION)"
else
    echo "Generating Python type support for rti.connext $RTI_PYTHON_VERSION..."

    # Ensure rtiddsgen is available from NDDSHOME
    RTIDDSGEN="$NDDSHOME/bin/rtiddsgen"
    if [ ! -x "$RTIDDSGEN" ]; then
        echo "ERROR: rtiddsgen not found at $RTIDDSGEN"
        echo "  Ensure NDDSHOME points to a valid Connext installation."
        exit 1
    fi

    mkdir -p "$VERSIONED_DIR"

    # Query the runtime XTypes compliance mask so generated code matches
    XTYPES_MASK=$(python3 -c "import rti.connextdds as dds; print(hex(int(dds.compliance.get_xtypes_mask())))" 2>/dev/null || echo "")

    # Generate Python types for each IDL file
    for IDL_FILE in "$IDL_DIR"/*.idl; do
        IDL_BASENAME=$(basename "$IDL_FILE" .idl)
        echo "  Generating: $IDL_BASENAME..."
        if [ -n "$XTYPES_MASK" ]; then
            "$RTIDDSGEN" -language Python -d "$VERSIONED_DIR" \
                -I "$IDL_DIR" -xTypesComplianceMask "$XTYPES_MASK" \
                "$IDL_FILE" -replace 2>&1 | grep -v "^$" || true
        else
            "$RTIDDSGEN" -language Python -d "$VERSIONED_DIR" \
                -I "$IDL_DIR" "$IDL_FILE" -replace 2>&1 | grep -v "^$" || true
        fi
    done

    # Create __init__.py if not generated
    if [ ! -f "$VERSIONED_DIR/__init__.py" ]; then
        touch "$VERSIONED_DIR/__init__.py"
    fi

    if [ ! -f "$VERSIONED_DIR/ExampleTypes.py" ]; then
        echo "ERROR: Type generation failed. ExampleTypes.py not created."
        exit 1
    fi

    GENERATED_VERSION=$(check_generated_version "$VERSIONED_DIR/ExampleTypes.py")
    echo "✓ Generated types using rtiddsgen $GENERATED_VERSION"
fi

# --- Run Application ---
echo
echo "Starting Example I/O Application..."
echo "-----------------------------------"
# Set the versioned types path so the app can find python_gen package
export DDS_PYTHON_GEN_DIR="$TYPES_CACHE_DIR/$RTI_PYTHON_VERSION"
export PYTHONPATH="$TYPES_CACHE_DIR/$RTI_PYTHON_VERSION:$PYTHONPATH"
cd "$SCRIPT_DIR"
python3 example_io_app.py "$@"
