#!/usr/bin/env python3
"""
Reproducer: Recording Service monitoring deserialization failure.

Demonstrates that DynamicData types loaded from XML (generated via
`rtiddsgen -convertToXml` from $NDDSHOME/resource/idl/) match the
Recording Service publisher but fail to deserialize because the
generated XML contains symbolic caseDiscriminator references that the
C-level XCDR interpreter cannot resolve.

Prerequisites:
  - RTI Connext DDS 7.3.1 installed at $NDDSHOME
  - rti.connext 7.3.1 Python package installed
  - Recording Service running on the same domain (default 0):

      rtirecordingservice -cfgFile reproducer_recorder.xml \\
        -cfgName reproducer -DDOMAIN_ID=0 -DADMIN_DOMAIN_ID=0

Usage:
  python3 reproducer.py [--domain 0]
"""

import argparse
import os
import sys
import time

import rti.connextdds as dds


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
XML_TYPES_DIR = os.path.join(SCRIPT_DIR, "xml_types")

MONITORING_TOPICS = {
    "config": {
        "topic": "rti/service/monitoring/config",
        "type": "RTI::Service::Monitoring::Config",
        "reliability": dds.ReliabilityKind.RELIABLE,
        "durability": dds.DurabilityKind.TRANSIENT_LOCAL,
    },
    "event": {
        "topic": "rti/service/monitoring/event",
        "type": "RTI::Service::Monitoring::Event",
        "reliability": dds.ReliabilityKind.RELIABLE,
        "durability": dds.DurabilityKind.TRANSIENT_LOCAL,
    },
    "periodic": {
        "topic": "rti/service/monitoring/periodic",
        "type": "RTI::Service::Monitoring::Periodic",
        "reliability": dds.ReliabilityKind.BEST_EFFORT,
        "durability": dds.DurabilityKind.VOLATILE,
    },
}


def load_xml_types():
    """Load monitoring types from XML generated by rtiddsgen -convertToXml."""
    xml_file = os.path.join(XML_TYPES_DIR, "ServiceMonitoring.xml")
    if not os.path.isfile(xml_file):
        print(f"ERROR: XML types not found at {xml_file}")
        print("Generate them with:")
        print("  cd $NDDSHOME/resource/idl")
        print("  rtiddsgen -convertToXml ServiceCommon.idl")
        print("  rtiddsgen -convertToXml RoutingServiceMonitoring.idl")
        print("  rtiddsgen -convertToXml RecordingServiceMonitoring.idl")
        print("  rtiddsgen -convertToXml ServiceMonitoring.idl")
        sys.exit(1)

    provider = dds.QosProvider(xml_file)
    types = {}
    for key, cfg in MONITORING_TOPICS.items():
        types[key] = provider.type(cfg["type"])
        print(f"  Loaded type: {cfg['type']} (name={types[key].name})")
    return types


def inspect_union_labels(types):
    """Show that the DynamicType correctly resolves discriminator labels."""
    print("\n--- Union discriminator labels (resolved by QosProvider) ---")
    for key, dtype in types.items():
        for m in dtype.members():
            if m.name == "value":
                union_type = m.type
                print(f"\n  {key} -> {union_type.name}:")
                for um in union_type.members():
                    print(f"    {um.name}: labels={list(um.labels)}")
                break


def test_matching_and_deserialization(domain_id, types):
    """Create readers, verify matching, attempt deserialization."""
    qos = dds.DomainParticipantQos()
    qos.database.shutdown_cleanup_period = dds.Duration.from_milliseconds(10)
    participant = dds.DomainParticipant(domain_id, qos=qos)
    subscriber = dds.Subscriber(participant)

    readers = {}
    for key, cfg in MONITORING_TOPICS.items():
        topic = dds.DynamicData.Topic(
            participant, cfg["topic"], types[key]
        )
        reader_qos = dds.DataReaderQos()
        reader_qos.reliability.kind = cfg["reliability"]
        reader_qos.durability.kind = cfg["durability"]

        reader = dds.DynamicData.DataReader(subscriber, topic, reader_qos)
        readers[key] = reader
        print(f"  Created reader: {cfg['topic']} "
              f"(type_name={topic.type_name})")

    print(f"\nWaiting 5 seconds for matching...")
    time.sleep(5)

    print("\n--- Results ---")
    any_data = False
    for key, reader in readers.items():
        pubs = reader.matched_publications
        print(f"\n  {MONITORING_TOPICS[key]['topic']}:")
        print(f"    matched_publications = {len(pubs)}")

        if len(pubs) > 0:
            # Attempt to read — this is where deserialization fails
            sample_count = 0
            for data, sinfo in reader.take():
                if sinfo.valid:
                    sample_count += 1
                    any_data = True
                    print(f"    SAMPLE: {str(data)[:300]}")
            if sample_count == 0:
                print("    No valid samples (deserialization likely failed — "
                      "check stderr for XCDR errors)")
        else:
            print("    (no match — is Recording Service running "
                  f"on domain {domain_id}?)")

    # Cleanup
    for reader in readers.values():
        reader.close()
    participant.close()

    return any_data


def main():
    parser = argparse.ArgumentParser(
        description="Reproducer: Recording Service monitoring "
                    "deserialization failure"
    )
    parser.add_argument(
        "-d", "--domain", type=int, default=0,
        help="DDS domain ID (must match Recording Service admin domain)"
    )
    args = parser.parse_args()

    print("=" * 60)
    print("Reproducer: Recording Service Monitoring Type Issue")
    print("=" * 60)

    print(f"\nDomain: {args.domain}")
    print(f"XML types dir: {XML_TYPES_DIR}")

    # Step 1: Load types from XML
    print("\n[1] Loading types from XML...")
    types = load_xml_types()

    # Step 2: Show that labels are correctly resolved at the DynamicType level
    inspect_union_labels(types)

    # Step 3: Test matching and deserialization
    print("\n[2] Creating readers and testing...")
    got_data = test_matching_and_deserialization(args.domain, types)

    # Summary
    print("\n" + "=" * 60)
    if got_data:
        print("SUCCESS: Received monitoring data.")
    else:
        print("FAILURE: Matched but deserialization failed.")
        print()
        print("The C-level XCDR interpreter reports 'Unknown union")
        print("discriminator value 20000' because rtiddsgen -convertToXml")
        print("emits symbolic caseDiscriminator references like:")
        print('  value="(RTI::Service::Monitoring::RECORDING_SERVICE)"')
        print("which are not resolved to literal integers (20000) at the")
        print("serialization layer.")
    print("=" * 60)


if __name__ == "__main__":
    main()
