"""Dear PyGui-facing shell helpers for rs_gui_v2."""

from .factory import (
    GuiShellAssembly,
    GuiShellSessionFactoryConfig,
    GuiShellSessionMode,
    build_default_gui_shell_session,
    build_gui_shell_assembly,
)
from .scheduler import UiFrameScheduler
from .session import GuiShellSession, GuiShellSessionConfig
from .workspace import GuiWorkspaceController, GuiWorkspaceControllerConfig
from .main_window import build_workspace_action_command
from .tabs import (
    PlotsTabController,
    PlotsTabControllerConfig,
    RecordTabController,
    RecordTabControllerConfig,
    ReplayActionView,
    ReplayTargetRow,
    ReplayTabController,
    ReplayTabControllerConfig,
    ReplayTabViewModel,
    ReplayTimelineRow,
    TopicsTabController,
    TopicsTabControllerConfig,
    build_mock_replay_tab_view_model,
    build_replay_action_command,
    build_replay_tab_view_model,
    plots_inputs_from_data_session_snapshot,
    topics_inputs_from_data_session_snapshot,
)
from .tabs.plots_tab import (
    PlotActionView,
    PlotPointRow,
    PlotRow,
    PlotSeriesRow,
    PlotsTabViewModel,
    build_mock_plots_tab_view_model,
    build_plots_tab_view_model,
)
from .tabs.topics_tab import (
    SampleInspectorRow,
    TopicActionView,
    TopicFieldRow,
    TopicRow,
    TopicsTabViewModel,
    build_topic_action_command,
    build_topic_field_command,
    build_topic_select_command,
    build_mock_topics_tab_view_model,
    build_topics_tab_view_model,
)
from .view_models import (
    EventLogEntry,
    ShellStatusItem,
    ShellViewModel,
    build_mock_shell_view_model,
    build_shell_view_model,
)

__all__ = [
    "EventLogEntry",
    "GuiShellAssembly",
    "GuiShellSession",
    "GuiShellSessionConfig",
    "GuiShellSessionFactoryConfig",
    "GuiShellSessionMode",
    "GuiWorkspaceController",
    "GuiWorkspaceControllerConfig",
    "PlotActionView",
    "PlotPointRow",
    "PlotRow",
    "PlotSeriesRow",
    "PlotsTabController",
    "PlotsTabControllerConfig",
    "PlotsTabViewModel",
    "RecordTabController",
    "RecordTabControllerConfig",
    "ReplayActionView",
    "ReplayTargetRow",
    "ReplayTabController",
    "ReplayTabControllerConfig",
    "ReplayTabViewModel",
    "ReplayTimelineRow",
    "SampleInspectorRow",
    "ShellStatusItem",
    "ShellViewModel",
    "TopicActionView",
    "TopicFieldRow",
    "TopicRow",
    "TopicsTabController",
    "TopicsTabControllerConfig",
    "TopicsTabViewModel",
    "UiFrameScheduler",
    "build_default_gui_shell_session",
    "build_gui_shell_assembly",
    "build_mock_plots_tab_view_model",
    "build_mock_replay_tab_view_model",
    "build_mock_shell_view_model",
    "build_mock_topics_tab_view_model",
    "build_plots_tab_view_model",
    "build_replay_action_command",
    "build_replay_tab_view_model",
    "build_workspace_action_command",
    "build_shell_view_model",
    "build_topic_action_command",
    "build_topic_field_command",
    "build_topic_select_command",
    "build_topics_tab_view_model",
    "plots_inputs_from_data_session_snapshot",
    "topics_inputs_from_data_session_snapshot",
]
