# (c) Copyright, Real-Time Innovations, 2025.  All rights reserved.
# RTI grants Licensee a license to use, modify, compile, and create derivative
# works of the software solely for use with RTI Connext DDS. Licensee may
# redistribute copies of the software provided that all such copies are subject
# to this license. The software is provided "as is", with no warranty of any
# type, including any warranty for fitness for any purpose. RTI is under no
# obligation to maintain or support the software. RTI shall not be liable for
# any incidental or consequential damages arising out of the use or inability
# to use the software.

"""
Recording Service Remote Control - Python

Remotely control an RTI Recording Service instance using the common
Remote Administration Platform via DDS Request/Reply with DynamicData.

Based on the C++ example:
https://github.com/rticommunity/rticonnextdds-examples/tree/master/examples/recording_service/service_admin/c%2B%2B11

Supported commands:
  - start/stop/pause Recording Service
  - set timestamp tags for recording
  - shutdown the service

Prerequisites:
  - Run setup.sh first to generate XML type files from IDL
  - Recording Service must be running with remote administration enabled

Usage examples:
  # Pause recording
  python3 recording_service_control.py pause

  # Resume (start) recording
  python3 recording_service_control.py start

  # Set a timestamp tag
  python3 recording_service_control.py tag "my_tag_name" --tag-description "Optional description"

  # Shutdown Recording Service
  python3 recording_service_control.py shutdown

  # Use a different domain ID
  python3 recording_service_control.py pause --domain-id 54

  # Specify a custom service name (default: remote_admin)
  python3 recording_service_control.py pause --service-name my_recorder
"""

import os
import sys
import time
import argparse

import rti.connextdds as dds
import rti.request as request


# ---------------------------------------------------------------------------
# Constants matching ServiceAdmin.idl
# ---------------------------------------------------------------------------
COMMAND_REQUEST_TOPIC_NAME = "rti/service/admin/command_request"
COMMAND_REPLY_TOPIC_NAME = "rti/service/admin/command_reply"

# CommandActionKind enum values
ACTION_CREATE = 0
ACTION_GET = 1
ACTION_UPDATE = 2
ACTION_DELETE = 3

# CommandReplyRetcode enum values
RETCODE_OK = 0
RETCODE_ERROR = 1

# Defaults
DEFAULT_DOMAIN_ID = 0
DEFAULT_SERVICE_NAME = "remote_admin"
DEFAULT_REPLY_TIMEOUT_SEC = 60
DISCOVERY_WAIT_SEC = 60
DISCOVERY_POLL_MS = 50


class RecordingServiceController:
    """
    Sends remote administration commands to an RTI Recording Service instance
    using the DDS Request/Reply pattern with DynamicData (loaded from XML types
    generated by rtiddsgen from the RTI-provided IDL files).
    """

    def __init__(self, domain_id: int = DEFAULT_DOMAIN_ID,
                 service_name: str = DEFAULT_SERVICE_NAME,
                 xml_types_dir: str = None,
                 qos_file: str = None):
        """
        Initialize the controller.

        Args:
            domain_id: DDS domain ID for remote administration (must match
                       the service's administration domain).
            service_name: The Recording Service configuration name
                          (e.g. "remote_admin").
            xml_types_dir: Path to directory containing the XML type files
                           generated by setup.sh. Defaults to ./xml_types.
            qos_file: Path to ServiceAdmin_QOS_PROFILES.xml. Defaults to the one
                       shipped alongside this script.
        """
        script_dir = os.path.dirname(os.path.abspath(__file__))

        if xml_types_dir is None:
            xml_types_dir = os.path.join(script_dir, "xml_types")
        if qos_file is None:
            qos_file = os.path.join(script_dir, "ServiceAdmin_QOS_PROFILES.xml")

        # Validate paths
        admin_xml = os.path.join(xml_types_dir, "ServiceAdmin.xml")
        rec_xml = os.path.join(xml_types_dir, "RecordingServiceTypes.xml")
        for path in [admin_xml, rec_xml, qos_file]:
            if not os.path.isfile(path):
                raise FileNotFoundError(
                    f"Required file not found: {path}\n"
                    "Run setup.sh first to generate XML type files."
                )

        self._domain_id = domain_id
        self._service_name = service_name

        # ── Load DynamicTypes from XML ──────────────────────────────────
        admin_provider = dds.QosProvider(admin_xml)
        self._request_type = admin_provider.type(
            "RTI::Service::Admin::CommandRequest"
        )
        self._reply_type = admin_provider.type(
            "RTI::Service::Admin::CommandReply"
        )

        rec_provider = dds.QosProvider(rec_xml)
        self._data_tag_type = rec_provider.type(
            "RTI::RecordingService::DataTagParams"
        )

        # ── Load QoS ────────────────────────────────────────────────────
        qos_provider = dds.QosProvider(qos_file)
        writer_qos = qos_provider.datawriter_qos_from_profile(
            "ServiceAdministrationProfiles::ServiceAdminRequesterProfile"
        )
        reader_qos = qos_provider.datareader_qos_from_profile(
            "ServiceAdministrationProfiles::ServiceAdminRequesterProfile"
        )

        # ── Create DomainParticipant and Requester ──────────────────────
        self._participant = dds.DomainParticipant(domain_id)

        self._requester = request.Requester(
            request_type=self._request_type,
            reply_type=self._reply_type,
            participant=self._participant,
            request_topic=COMMAND_REQUEST_TOPIC_NAME,
            reply_topic=COMMAND_REPLY_TOPIC_NAME,
            datawriter_qos=writer_qos,
            datareader_qos=reader_qos,
        )

        print(f"[RecordingServiceController] Initialized on domain {domain_id}")
        print(f"  Service name: {service_name}")

    # ------------------------------------------------------------------
    # Public command helpers
    # ------------------------------------------------------------------

    def start(self):
        """Resume / start the Recording Service."""
        return self._send_state_command("running")

    def pause(self):
        """Pause the Recording Service."""
        return self._send_state_command("paused")

    def shutdown(self):
        """Shut down the Recording Service (DELETE command)."""
        resource = f"/recording_services/{self._service_name}"
        return self._send_command(ACTION_DELETE, resource, "")

    def tag_timestamp(self, tag_name: str, tag_description: str = ""):
        """
        Create a timestamp tag in the Recording Service database.

        Tags can later be used to symbolically define time ranges for
        replay or conversion.

        Args:
            tag_name: Name for the tag.
            tag_description: Optional description.
        """
        resource = (
            f"/recording_services/{self._service_name}"
            "/storage/sqlite:tag_timestamp"
        )

        # Build DataTagParams DynamicData and serialize to CDR
        tag_data = dds.DynamicData(self._data_tag_type)
        tag_data["timestamp_offset"] = 0.0
        tag_data["tag_name"] = tag_name
        tag_data["tag_description"] = tag_description
        cdr_buffer = tag_data.to_cdr_buffer()

        # Convert CharSeq to list of ints for the octet_body field
        octet_body = [ord(c) if isinstance(c, str) else c for c in cdr_buffer]

        return self._send_command(
            ACTION_UPDATE, resource, "", octet_body=octet_body
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _send_state_command(self, state: str):
        """Send an UPDATE command to change the service state."""
        resource = f"/recording_services/{self._service_name}/state"
        return self._send_command(ACTION_UPDATE, resource, state)

    def _send_command(self, action: int, resource: str, string_body: str,
                      octet_body: list = None):
        """
        Build a CommandRequest, wait for discovery, send it, and wait
        for a reply.

        Args:
            action: CommandActionKind enum value.
            resource: Resource identifier path.
            string_body: String body argument of the command.
            octet_body: Optional list of ints for the octet_body field.

        Returns:
            dict with 'retcode', 'native_retcode', and 'string_body'
            from the reply.
        """
        # Build the request
        cmd = dds.DynamicData(self._request_type)
        cmd["instance_id"] = 0
        cmd["action"] = action
        cmd["resource_identifier"] = resource
        cmd["string_body"] = string_body
        if octet_body is not None:
            cmd["octet_body"] = octet_body

        print(f"\n[Command] Sending request:")
        print(f"  Action:   {_action_name(action)}")
        print(f"  Resource: {resource}")
        if string_body:
            print(f"  Body:     {string_body}")

        # ── Wait for discovery ──────────────────────────────────────────
        self._wait_for_match()

        # ── Send request ────────────────────────────────────────────────
        request_id = self._requester.send_request(cmd)
        print("[Command] Request sent, waiting for reply...")

        # ── Wait for reply ──────────────────────────────────────────────
        got_reply = self._requester.wait_for_replies(
            dds.Duration.from_seconds(DEFAULT_REPLY_TIMEOUT_SEC),
            min_count=1,
            related_request_id=request_id,
        )

        if not got_reply:
            print("[Command] ERROR: No reply received "
                  f"(timeout {DEFAULT_REPLY_TIMEOUT_SEC}s)")
            return None

        replies = self._requester.take_replies(request_id)
        print(f"[Command] Received {len(replies)} reply(ies):")

        result = None
        for i, sample in enumerate(replies):
            if sample.info.valid:
                retcode = sample.data["retcode"]
                native = sample.data["native_retcode"]
                body = sample.data["string_body"]

                retcode_str = "OK" if retcode == RETCODE_OK else "ERROR"
                print(f"  Reply {i+1}: retcode={retcode_str}, "
                      f"native_retcode={native}, "
                      f"string_body=\"{body}\"")

                result = {
                    "retcode": retcode,
                    "native_retcode": native,
                    "string_body": body,
                }
            else:
                print(f"  Reply {i+1}: [invalid sample]")

        return result

    def _wait_for_match(self):
        """
        Wait until request writer and reply reader have each matched
        at least one endpoint (the Recording Service).
        """
        writer = self._requester.request_datawriter
        reader = self._requester.reply_datareader

        deadline = time.time() + DISCOVERY_WAIT_SEC

        # Wait for publication match (writer → service reader)
        while writer.publication_matched_status.current_count < 1:
            if time.time() > deadline:
                raise TimeoutError(
                    "Timed out waiting for request writer to match "
                    "a Recording Service subscriber. Is the service "
                    "running with remote administration enabled?"
                )
            time.sleep(DISCOVERY_POLL_MS / 1000.0)

        # Wait for subscription match (reader ← service writer)
        while reader.subscription_matched_status.current_count < 1:
            if time.time() > deadline:
                raise TimeoutError(
                    "Timed out waiting for reply reader to match "
                    "a Recording Service publisher."
                )
            time.sleep(DISCOVERY_POLL_MS / 1000.0)

        print("[Discovery] Matched with Recording Service")

    def close(self):
        """Clean up DDS resources."""
        try:
            # Delete requester first so its internal waitset is detached
            del self._requester
        except Exception:
            pass
        try:
            self._participant.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _action_name(action: int) -> str:
    names = {
        ACTION_CREATE: "CREATE",
        ACTION_GET: "GET",
        ACTION_UPDATE: "UPDATE",
        ACTION_DELETE: "DELETE",
    }
    return names.get(action, f"UNKNOWN({action})")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Remotely control an RTI Recording Service instance",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s start                              # Resume recording
  %(prog)s pause                              # Pause recording
  %(prog)s shutdown                           # Shut down the service
  %(prog)s tag "my_tag" -td "A description"   # Set a timestamp tag
  %(prog)s pause --domain-id 54               # Use domain 54
  %(prog)s pause --service-name my_recorder   # Custom service name
""",
    )

    parser.add_argument(
        "command",
        choices=["start", "pause", "shutdown", "tag"],
        help="Command to send to the Recording Service",
    )

    parser.add_argument(
        "tag_name",
        nargs="?",
        default=None,
        help="Tag name (required for 'tag' command)",
    )

    parser.add_argument(
        "-td", "--tag-description",
        default="",
        help="Tag description (optional, used with 'tag' command)",
    )

    parser.add_argument(
        "-d", "--domain-id",
        type=int,
        default=DEFAULT_DOMAIN_ID,
        help=f"DDS domain ID for administration (default: {DEFAULT_DOMAIN_ID})",
    )

    parser.add_argument(
        "-s", "--service-name",
        default=DEFAULT_SERVICE_NAME,
        help=f"Recording Service configuration name (default: {DEFAULT_SERVICE_NAME})",
    )

    parser.add_argument(
        "-v", "--verbosity",
        type=int,
        default=1,
        choices=[0, 1, 2, 3, 4, 5],
        help="Connext logging verbosity 0=SILENT..5=ALL (default: 1)",
    )

    args = parser.parse_args()

    # Validate tag command
    if args.command == "tag" and not args.tag_name:
        parser.error("The 'tag' command requires a tag_name argument")

    # Set Connext verbosity
    verbosity_levels = {
        0: dds.Verbosity.SILENT,
        1: dds.Verbosity.EXCEPTION,
        2: dds.Verbosity.WARNING,
        3: dds.Verbosity.STATUS_LOCAL,
        4: dds.Verbosity.STATUS_REMOTE,
        5: dds.Verbosity.STATUS_ALL,
    }
    dds.Logger.instance.verbosity = verbosity_levels.get(
        args.verbosity, dds.Verbosity.EXCEPTION
    )

    # Run
    controller = None
    try:
        controller = RecordingServiceController(
            domain_id=args.domain_id,
            service_name=args.service_name,
        )

        if args.command == "start":
            controller.start()
        elif args.command == "pause":
            controller.pause()
        elif args.command == "shutdown":
            controller.shutdown()
        elif args.command == "tag":
            controller.tag_timestamp(args.tag_name, args.tag_description)

    except KeyboardInterrupt:
        print("\nInterrupted by user.")
    except Exception as e:
        print(f"\nERROR: {e}", file=sys.stderr)
        return 1
    finally:
        if controller is not None:
            controller.close()

    return 0


if __name__ == "__main__":
    sys.exit(main())
